-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 18:35:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema workersdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `workersdb` ;

-- -----------------------------------------------------
-- Schema workersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workersdb` DEFAULT CHARACTER SET utf8 ;
USE `workersdb` ;

-- -----------------------------------------------------
-- Table `workersdb`.`worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workersdb`.`worker` ;

CREATE TABLE IF NOT EXISTS `workersdb`.`worker` (
  `idWorker` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idWorker`),
  UNIQUE INDEX `idWorker_UNIQUE` (`idWorker` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workersdb`.`work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workersdb`.`work` ;

CREATE TABLE IF NOT EXISTS `workersdb`.`work` (
  `idWork` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idWork`),
  UNIQUE INDEX `idWork_UNIQUE` (`idWork` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workersdb`.`worker_work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workersdb`.`worker_work` ;

CREATE TABLE IF NOT EXISTS `workersdb`.`worker_work` (
  `idWorker` INT NOT NULL,
  `idWork` INT NOT NULL,
  `workDay` INT NOT NULL,
  `startWork` DATETIME NOT NULL,
  `salary` DOUBLE NOT NULL,
  PRIMARY KEY (`idWorker`, `idWork`),
  INDEX `fk_worker_work_work1_idx` (`idWork` ASC) VISIBLE,
  CONSTRAINT `fk_worker_work_worker`
    FOREIGN KEY (`idWorker`)
    REFERENCES `workersdb`.`worker` (`idWorker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_worker_work_work1`
    FOREIGN KEY (`idWork`)
    REFERENCES `workersdb`.`work` (`idWork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
